# Site settings

url: "https://waynegraham.github.io"
title: "{ Wayne Graham }"
description: "Blog and website of Wayne Graham, blogging mainly for digital humanities and tech. Opinions expressed are mine."
keywords: "wayne, graham, wayne graham, digital humanities, humanities, 3D, technology, computer science, scholars' lab, scholars, virginia"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-46274579-1"
disqus-shortname: "waynegrahamatgithubio"

# Gems for Github Pages
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Projects: 'projects'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/scholarslab.png"
    date: "February 2009 - Today"
    description: "Head of Research & Development @ <a href=\"http://scholarslab.org\" target=\"_blank\">Scholars\' Lab</a>, working on geospatatial projects like Neatline and Geoblacklight; mentoring graduate fellows; teaching software development, photogrammetry, 3D visualization, and spatial interpretation."
  - image: "/img/career/gilchrist-seal.jpg"
    date: "April 2002 - January 2009"
    description: "Emerging Technology Coordinator @ the <a href=\"http://swem.wm.edu\" target=\"_blank\">Earl Gregg Swem Library, College of William and Mary</a>. Worked on next-generation library search interfaces (<a href=\"http://vufind.org\">vufind</a>, <a href=\"http://projectblacklight.org\">Project Blacklight</a>, helped implement computer graphics and scientific visualization center, and implemented institutional repository infrastructure."
  - image: "/img/career/Colonial_Williamsburg_Logo.jpg"
    date: "May 2000 - March 2002"
    description: "Research Assistant @ the <a href=\"http://research.history.org\" target=\"_blank\">Colonial Williamsburg Foundation's Department of Historical Research</a> working on digitizing the Foundation's collection of 17<sup>th</sup> and 18<sup>th</sup> century manuscripts, digital mapping, and artifact database."
  - image: "/img/career/william-and-mary.png"
    date: "August 1999 - May 2001"
    description: "Master of Arts @ the <a href=\"http://www.wm.edu/as/history/gradprogram/\" target=\"_blank\">College of William & Mary</a> in History. My research focused on wealth distribution on the Virginia frontier during the US Colonial period."
  - image: "/img/career/vmi.jpg"
    date: "August 1995 - May 1999"
    description: "Bachelor of Arts @ <a href=\"http://www.vmi.edu\" target=\"_blank\">Virginia Military Institute</a> in History and a minor in Business. Graduated with <em>Honors</em> and <em>Distinction</em>."

# First image of the Career timeline
career-img: "/img/career/wayne_icon.png"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/waynegraham"
  - title: "linkedin"
    url: "https://www.linkedin.com/pub/wayne-graham/9/59/170"
  - title: "youtube"
    url: "http://youtube.com/c/phybernightmare"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", "package.json", "node_modules"]
